## LANGUAGE
defaultContentLanguage: fr

## ADVANCED
build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true
enableRobotsTXT: true
imaging:
  quality: 90
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 6
removePathAccents: true
timeout: 100000
