## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
build:
  buildStats:
    disableClasses: false
    disableIDs: true
    disableTags: false
    enable: true
enableRobotsTXT: true
imaging:
  quality: 90
markup:
  tableOfContents:
    ordered: true
paginate: 6
removePathAccents: true