_merge: deep
animation: true
hero:
  _merge: deep
  cover: "x600"
  cover_mobile: "x400"
persons:
  _merge: deep
  image:
    _merge: deep
    desktop: "499x499"
    mobile: "300x300"
  thumbnail:
    _merge: deep
    desktop: "515x465"
posts:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "499x499"
    mobile: "300x300"
blocks:
  _merge: deep
  quote:
    _merge: deep
    desktop: "1023x767"
