_merge: deep
animation: true
hero:
  _merge: deep
  cover: "1920x600"
  cover_home: "1920x1080"
  cover_mobile: "360x"
persons:
  _merge: deep
  image:
    _merge: deep
    desktop: "499x499"
    mobile: "300x300"
  thumbnail:
    _merge: deep
    desktop: "515x465"
posts:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "499x499"
    mobile: "300x300"
publications:
  _merge: deep
  thumbnail:
    _merge: deep
    desktop: "512x390"
    mobile: "300x229"
blocks:
  _merge: deep
  quote:
    _merge: deep
    desktop: "1023x767"
