_merge: deep
persons: notre-equipe/:slug
statutes: notre-equipe/:slug
posts: actualite/:year-:month-:day-:slug
categories: actualite/:slug
publications: blog/:year-:month-:day-:slug
publications_authors: blog/:slug
publications_categories: blog/:slug
